### ISSUE TITLE
Phone resets keyboard layout from time to time

### ISSUE THREAD

**Issue by jklingen** [kimmoli/tohkbd2#49]
Every once in a while, I find my phone suddenly using QWERTY instead of the QWERTZ layout I normally use. Interestingly after opening TOHKBD settings UI it still shows QWERTZ as "active", but nevertheless I need to select it again to actually have it active.

Unfortunately, I haven't yet been able to find how to reproduce this. It does not seem to be related to reboot or detachment of keyboard/TOH.
Is this a known issue? If not, I'll do some more testing to see if I can make it forget in a repeatable way.

**Comment by kimmoli** [comment]
If you are using the harbour version of tohkbd (aka master branch, version 0.4.x) it is already completely rewritten from layout change related parts.

**Comment by jklingen** [comment]
I am using 0.4.2 already from harbour/store. Guess that means that I should do some more testing to see if I can enforce the behavior. I'll let you know when I found a way.

**Comment by kimmoli** [comment]
I meant to say, in coming 0.5.x version the layout changing system is completely different from 0.4.x, and uses physical layout setting from Jolla settings. This thing is available in Jolla settings UI, but does not really yet work on Sailfish 1.1.7.x, and therefore i haven't yet published version 0.5.x of tohkbd2.

But if you want, you can pursue for the root cause of your issue (i wouldn't spend much hours for it)

**Comment by jklingen** [comment]
Thanks for clarification. As SF2 (hopefully) will arrive soon, I don't think it makes much sense to look into this any deeper - actually it's just a minor annoyance for me.

However, if you would like to have further information about the issue, just let me know and I'll see what I can find :)

Thanks a lot
